import { Component } from '@angular/core';

@Component({
  selector: 'employee-table',
  templateUrl: './employeeTable.component.html',
  styleUrl:'./employeeTable.component.css'
})
export class EmployeeTableComponent {
  employees = [
    {
      email: 'sarah.james@example.com',
      employeeId: 'EMP001',
      employeeName: 'Sarah James',
      designation: 'Product Manager',
      phone: '+1 408-832-3111',
      manager: 'Robert Brown',
    },
    {
      email: 'noah.johnson@example.com',
      employeeId: 'EMP002',
      employeeName: 'Noah Johnson',
      designation: 'Frontend Developer',
      phone: '+1 752-123-9361',
      manager: 'Robert Brown',
    },
    {
      email: 'john.lee@example.com',
      employeeId: 'EMP003',
      employeeName: 'John Lee',
      designation: 'DevOps Engineer',
      phone: '+1 784-883-2844',
      manager: 'Alice Johnson',
    },
    {
      email: 'sarah.baker@example.com',
      employeeId: 'EMP004',
      employeeName: 'Sarah Baker',
      designation: 'Backend Developer',
      phone: '+1 840-747-5348',
      manager: 'James Anderson',
    },
    {
      email: 'sarah.williams@example.com',
      employeeId: 'EMP005',
      employeeName: 'Sarah Williams',
      designation: 'Product Manager',
      phone: '+1 336-545-1989',
      manager: 'James Anderson',
    },
    {
      email: 'chris.evans@example.com',
      employeeId: 'EMP006',
      employeeName: 'Chris Evans',
      designation: 'Frontend Developer',
      phone: '+1 623-886-8580',
      manager: 'Robert Brown',
    },
    {
      email: 'chris.williams@example.com',
      employeeId: 'EMP007',
      employeeName: 'Chris Williams',
      designation: 'Product Manager',
      phone: '+1 260-894-1750',
      manager: 'Sophia Taylor',
    },
    {
      email: 'john.james@example.com',
      employeeId: 'EMP008',
      employeeName: 'John James',
      designation: 'System Administrator',
      phone: '+1 674-868-4992',
      manager: 'Alice Johnson',
    },
    {
      email: 'jane.martin@example.com',
      employeeId: 'EMP009',
      employeeName: 'Jane Martin',
      designation: 'DevOps Engineer',
      phone: '+1 312-877-6858',
      manager: 'James Anderson',
    },
    {
      email: 'noah.baker@example.com',
      employeeId: 'EMP010',
      employeeName: 'Noah Baker',
      designation: 'Data Scientist',
      phone: '+1 627-876-5400',
      manager: 'Alice Johnson',
    },
    {
      email: 'emma.doe@example.com',
      employeeId: 'EMP011',
      employeeName: 'Emma Doe',
      designation: 'System Administrator',
      phone: '+1 261-370-2401',
      manager: 'Alice Johnson',
    },
    {
      email: 'john.smith@example.com',
      employeeId: 'EMP012',
      employeeName: 'John Smith',
      designation: 'Software Engineer',
      phone: '+1 636-278-2335',
      manager: 'Sophia Taylor',
    },
    {
      email: 'michael.doe@example.com',
      employeeId: 'EMP013',
      employeeName: 'Michael Doe',
      designation: 'Quality Analyst',
      phone: '+1 172-511-5425',
      manager: 'Alice Johnson',
    },
    {
      email: 'olivia.lee@example.com',
      employeeId: 'EMP014',
      employeeName: 'Olivia Lee',
      designation: 'Frontend Developer',
      phone: '+1 990-615-4187',
      manager: 'Alice Johnson',
    },
    {
      email: 'laura.garcia@example.com',
      employeeId: 'EMP015',
      employeeName: 'Laura Garcia',
      designation: 'UI/UX Designer',
      phone: '+1 265-125-7574',
      manager: 'Robert Brown',
    },
    {
      email: 'laura.williams@example.com',
      employeeId: 'EMP016',
      employeeName: 'Laura Williams',
      designation: 'Product Manager',
      phone: '+1 311-685-1827',
      manager: 'Robert Brown',
    },
    {
      email: 'noah.johnson@example.com',
      employeeId: 'EMP017',
      employeeName: 'Noah Johnson',
      designation: 'UI/UX Designer',
      phone: '+1 928-164-1563',
      manager: 'James Anderson',
    },
    {
      email: 'sarah.doe@example.com',
      employeeId: 'EMP018',
      employeeName: 'Sarah Doe',
      designation: 'Frontend Developer',
      phone: '+1 889-546-9574',
      manager: 'James Anderson',
    },
    {
      email: 'sarah.evans@example.com',
      employeeId: 'EMP019',
      employeeName: 'Sarah Evans',
      designation: 'Frontend Developer',
      phone: '+1 774-915-6237',
      manager: 'Sophia Taylor',
    },
    {
      email: 'sarah.garcia@example.com',
      employeeId: 'EMP020',
      employeeName: 'Sarah Garcia',
      designation: 'Frontend Developer',
      phone: '+1 975-858-1137',
      manager: 'Alice Johnson',
    },
    {
      email: 'emma.doe@example.com',
      employeeId: 'EMP021',
      employeeName: 'Emma Doe',
      designation: 'UI/UX Designer',
      phone: '+1 789-156-6000',
      manager: 'Sophia Taylor',
    },
    {
      email: 'jane.evans@example.com',
      employeeId: 'EMP022',
      employeeName: 'Jane Evans',
      designation: 'System Administrator',
      phone: '+1 999-891-7993',
      manager: 'Robert Brown',
    },
    {
      email: 'michael.lee@example.com',
      employeeId: 'EMP023',
      employeeName: 'Michael Lee',
      designation: 'UI/UX Designer',
      phone: '+1 789-666-8534',
      manager: 'Robert Brown',
    },
    {
      email: 'emma.johnson@example.com',
      employeeId: 'EMP024',
      employeeName: 'Emma Johnson',
      designation: 'Quality Analyst',
      phone: '+1 752-708-1499',
      manager: 'Sophia Taylor',
    },
    {
      email: 'michael.lee@example.com',
      employeeId: 'EMP025',
      employeeName: 'Michael Lee',
      designation: 'Product Manager',
      phone: '+1 869-154-4161',
      manager: 'James Anderson',
    },
    {
      email: 'sarah.baker@example.com',
      employeeId: 'EMP026',
      employeeName: 'Sarah Baker',
      designation: 'Backend Developer',
      phone: '+1 156-939-2389',
      manager: 'Sophia Taylor',
    },
    {
      email: 'daniel.martin@example.com',
      employeeId: 'EMP027',
      employeeName: 'Daniel Martin',
      designation: 'UI/UX Designer',
      phone: '+1 897-118-4832',
      manager: 'Sophia Taylor',
    },
    {
      email: 'michael.james@example.com',
      employeeId: 'EMP028',
      employeeName: 'Michael James',
      designation: 'Data Scientist',
      phone: '+1 942-317-4871',
      manager: 'Alice Johnson',
    },
    {
      email: 'michael.james@example.com',
      employeeId: 'EMP029',
      employeeName: 'Michael James',
      designation: 'Quality Analyst',
      phone: '+1 603-231-3053',
      manager: 'James Anderson',
    },
    {
      email: 'jane.lee@example.com',
      employeeId: 'EMP030',
      employeeName: 'Jane Lee',
      designation: 'Product Manager',
      phone: '+1 320-525-7814',
      manager: 'Alice Johnson',
    },
    {
      email: 'olivia.johnson@example.com',
      employeeId: 'EMP031',
      employeeName: 'Olivia Johnson',
      designation: 'Data Scientist',
      phone: '+1 384-470-3073',
      manager: 'James Anderson',
    },
    {
      email: 'noah.williams@example.com',
      employeeId: 'EMP032',
      employeeName: 'Noah Williams',
      designation: 'UI/UX Designer',
      phone: '+1 694-558-3556',
      manager: 'James Anderson',
    },
    {
      email: 'chris.lee@example.com',
      employeeId: 'EMP033',
      employeeName: 'Chris Lee',
      designation: 'Software Engineer',
      phone: '+1 493-341-5183',
      manager: 'James Anderson',
    },
    {
      email: 'chris.smith@example.com',
      employeeId: 'EMP034',
      employeeName: 'Chris Smith',
      designation: 'Frontend Developer',
      phone: '+1 693-664-8072',
      manager: 'Robert Brown',
    },
    {
      email: 'daniel.lee@example.com',
      employeeId: 'EMP035',
      employeeName: 'Daniel Lee',
      designation: 'Backend Developer',
      phone: '+1 888-898-8500',
      manager: 'Robert Brown',
    },
    {
      email: 'daniel.evans@example.com',
      employeeId: 'EMP036',
      employeeName: 'Daniel Evans',
      designation: 'System Administrator',
      phone: '+1 592-942-3649',
      manager: 'James Anderson',
    },
    {
      email: 'sarah.evans@example.com',
      employeeId: 'EMP037',
      employeeName: 'Sarah Evans',
      designation: 'UI/UX Designer',
      phone: '+1 266-715-7683',
      manager: 'James Anderson',
    },
    {
      email: 'jane.james@example.com',
      employeeId: 'EMP038',
      employeeName: 'Jane James',
      designation: 'Quality Analyst',
      phone: '+1 911-611-5245',
      manager: 'James Anderson',
    },
    {
      email: 'daniel.james@example.com',
      employeeId: 'EMP039',
      employeeName: 'Daniel James',
      designation: 'Software Engineer',
      phone: '+1 321-894-5993',
      manager: 'Robert Brown',
    },
    {
      email: 'chris.lee@example.com',
      employeeId: 'EMP040',
      employeeName: 'Chris Lee',
      designation: 'Frontend Developer',
      phone: '+1 438-396-8898',
      manager: 'Robert Brown',
    },
    {
      email: 'michael.williams@example.com',
      employeeId: 'EMP041',
      employeeName: 'Michael Williams',
      designation: 'Backend Developer',
      phone: '+1 193-546-4864',
      manager: 'Sophia Taylor',
    },
    {
      email: 'laura.james@example.com',
      employeeId: 'EMP042',
      employeeName: 'Laura James',
      designation: 'Product Manager',
      phone: '+1 680-890-5075',
      manager: 'Sophia Taylor',
    },
    {
      email: 'noah.smith@example.com',
      employeeId: 'EMP043',
      employeeName: 'Noah Smith',
      designation: 'DevOps Engineer',
      phone: '+1 488-273-1291',
      manager: 'Sophia Taylor',
    },
    {
      email: 'noah.evans@example.com',
      employeeId: 'EMP044',
      employeeName: 'Noah Evans',
      designation: 'Software Engineer',
      phone: '+1 615-605-9054',
      manager: 'Robert Brown',
    },
    {
      email: 'olivia.lee@example.com',
      employeeId: 'EMP045',
      employeeName: 'Olivia Lee',
      designation: 'Backend Developer',
      phone: '+1 456-523-7194',
      manager: 'James Anderson',
    },
    {
      email: 'laura.evans@example.com',
      employeeId: 'EMP046',
      employeeName: 'Laura Evans',
      designation: 'Frontend Developer',
      phone: '+1 223-722-5919',
      manager: 'Robert Brown',
    },
    {
      email: 'laura.garcia@example.com',
      employeeId: 'EMP047',
      employeeName: 'Laura Garcia',
      designation: 'Technical Lead',
      phone: '+1 910-531-2147',
      manager: 'Alice Johnson',
    },
    {
      email: 'olivia.smith@example.com',
      employeeId: 'EMP048',
      employeeName: 'Olivia Smith',
      designation: 'Data Scientist',
      phone: '+1 950-912-4919',
      manager: 'Sophia Taylor',
    },
    {
      email: 'laura.martin@example.com',
      employeeId: 'EMP049',
      employeeName: 'Laura Martin',
      designation: 'UI/UX Designer',
      phone: '+1 919-668-3261',
      manager: 'James Anderson',
    },
    {
      email: 'john.smith@example.com',
      employeeId: 'EMP050',
      employeeName: 'John Smith',
      designation: 'Quality Analyst',
      phone: '+1 161-312-7686',
      manager: 'Alice Johnson',
    },
  ];
  selectedEmployees = [];
  currentPage=1;
  pageSize=10;
  addReportee = (emp: any) => {};
  editDetails = (emp: any) => {};
  deleteEmployee = (emp: any) => {};
  changeReportingLine = (emp: any) => {};
}
